spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insurance?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hoon
    password: 58998972
    initialization-mode: always
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
